# TODO
path: 'data/tgs/irradiation'  # directory containing input files
idxs: null  # indices of files to fit (null for all)

# Signal Processing
signal_process:
  heterodyne: di-homodyne  # detection method: 'di-homodyne' or 'mono-homodyne'
  null_point: 1  # null point selection (valid range: 1-4)
  plot: false  # enable/disable processed signal visualization

# FFT Analysis
fft:
  signal_proportion: 0.9  # proportion of signal to analyze (0.0 to 1.0)
  duplicate_signal: false  # double the signal amplitude for analysis
  use_derivative: true  # use signal derivative instead of raw signal
  analysis_type: psd  # analysis method: 'psd' (power spectral density) or 'fft' (fast Fourier transform)

# Lorentzian Fitting
lorentzian:
  signal_proportion: 1.0  # proportion of signal to use for fitting (0.0 to 1.0)
  frequency_bounds: [0.1, 0.6]  # frequency range for fitting [GHz]
  dc_filter_range: [0, 12000]  # DC filtering range [Hz]
  bimodal_fit: false  # enable bimodal Lorentzian fitting
  plot: false  # enable/disable FFT and Lorentzian fit visualization

# TGS Fitting
tgs:
  grating_spacing: 3.5276  # TGS probe grating spacing [µm]
  signal_proportion: 0.1  # proportion of signal to use for fitting (0.0 to 1.0)
  plot: false  # enable/disable TGS fit visualization